name: CI
on:
  push:
    branches:
      - master
    tags:
      - "jq-*"
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          [
            ubuntu-22.04,
          ]
        arch:
          [
            amd64,
            arm64,
            armel,
            armhf,
            i386,
            mips,
            mips64,
            mips64el,
            mips64r6,
            mips64r6el,
            mipsel,
            mipsr6,
            mipsr6el,
            powerpc,
            ppc64el,
            s390x,
          ]
        include:
          - arch: amd64
            CC: "x86_64-linux-gnu"
            binutils: "binutils-x86-64-linux-gnu"
          - arch: arm64
            CC: "aarch64-linux-gnu"
            binutils: "binutils-aarch64-linux-gnu"
          - arch: armel
            CC: "arm-linux-gnueabi"
            binutils: "binutils-aarch64-linux-gnu"
          - arch: armhf
            CC: "arm-linux-gnueabihf"
            binutils: "binutils-arm-linux-gnueabi"
            strip: "arm-linux-gnueabihf-strip"
          - arch: i386
            CC: "i686-linux-gnu"
            binutils: "binutils-i686-linux-gnu"
            strip: "i686-linux-gnu-strip"
          - arch: mips
            CC: "mips-linux-gnu"
            binutils: "binutils-mips-linux-gnu"
            strip: "mips-linux-gnu-strip"
          - arch: mips64
            CC: "mips64-linux-gnuabi64"
            binutils: "binutils-mips64-linux-gnuabi64"
            strip: "mips64-linux-gnuabi64-strip"
          - arch: mips64el
            CC: "mips64el-linux-gnuabi64"
            binutils: "binutils-mips64el-linux-gnuabi64"
            strip: "mips64el-linux-gnuabi64-strip"
          - arch: mips64r6
            CC: "mipsisa64r6-linux-gnuabi64"
            binutils: "binutils-mipsisa64r6-linux-gnuabi64"
            strip: "mipsisa64r6-linux-gnuabi64-strip"
          - arch: mips64r6el
            CC: "mipsisa64r6el-linux-gnuabi64"
            binutils: "binutils-mipsisa64r6el-linux-gnuabi64"
            strip: "mipsisa64r6el-linux-gnuabi64-strip"
          - arch: mipsel
            CC: "mipsel-linux-gnu"
            binutils: "binutils-mipsel-linux-gnu"
            strip: "mipsel-linux-gnu-strip"
          - arch: mipsr6
            CC: "mipsisa32r6-linux-gnu"
            binutils: "binutils-mipsisa32r6-linux-gnu"
            strip: "mipsisa32r6-linux-gnu-strip"
          - arch: mipsr6el
            CC: "mipsisa32r6el-linux-gnu"
            binutils: "binutils-mipsisa32r6el-linux-gnu"
            strip: "mipsisa32r6el-linux-gnu-strip"
          - arch: powerpc
            CC: "powerpc-linux-gnu"
            binutils: "binutils-powerpc-linux-gnu"
            strip: "powerpc-linux-gnu-strip"
          - arch: ppc64el
            CC: "powerpc64le-linux-gnu"
            binutils: "binutils-powerpc64le-linux-gnu"
            strip: "powerpc64le-linux-gnu-strip"
          - arch: s390x
            CC: "s390x-linux-gnu"
            binutils: "binutils-s390x-linux-gnu"
            strip: "s390x-linux-gnu-strip"
    runs-on: ${{ matrix.image }}
    env:
      AR: ${{ matrix.CC }}-ar
      CHOST: ${{ matrix.cc }}
      CC: ${{ matrix.cc }}-gcc
      CPP: ${{ matrix.cc }}-cpp
      CXX: ${{ matrix.cc }}-g++
      SUFFIX: linux-${{ matrix.image }}-gcc-${{ matrix.arch }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y automake autoconf libtool crossbuild-essential-${{ matrix.arch }} ${{ matrix.binutils }}
      - name: Build
        run: |
          autoreconf -i
          ./configure \
            --host=${{ matrix.CC }} \
            --disable-docs \
            --disable-maintainer-mode \
            --disable-valgrind \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static
          make -j$(nproc)
          ${{ matrix.strip }} jq
          file ./jq
      - name: Test
        # Only run tests for amd64 matching the CI machine arch
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          make check
          git diff --exit-code
      - name: Upload Test Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ env.SUFFIX }}
          retention-days: 7
          path: |
            test-suite.log
            tests/*.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jq-${{ env.SUFFIX }}
          if-no-files-found: error
          retention-days: 7
          path: jq

  macos:
    strategy:
      fail-fast: false
      matrix:
        image:
          [
            macos-11,
            macos-12,
            macos-13,
          ]
        arch:
          [
            amd64,
            arm64,
          ]
        include:
          - arch: amd64
            target: "x86_64-apple-darwin"
          - arch: arm64
            target: "arm64-apple-darwin"
    runs-on: ${{ matrix.image }}
    env:
      SUFFIX: macos-${{ matrix.image }}-clang-${{ matrix.arch }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          # brew update sometimes fails with "Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!"
          brew update || brew update-reset
          brew install autoconf automake libtool
      - name: "Set CC"
        run: |
          echo "CC=clang -target ${{ matrix.target }}$(uname -r)" >> $GITHUB_ENV
      - name: Build
        run: |
          autoreconf -i
          ./configure \
            --host=${{ matrix.target }}$(uname -r) \
            --disable-docs \
            --disable-maintainer-mode \
            --disable-valgrind \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static
          make
          strip jq
          file ./jq
      - name: Test
        # Only run tests for amd64 matching the CI machine arch
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          make check
          git diff --exit-code
      - name: Upload Test Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ env.SUFFIX }}
          retention-days: 7
          path: |
            test-suite.log
            tests/*.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jq-${{ env.SUFFIX }}
          if-no-files-found: error
          retention-days: 7
          path: jq

  windows:
    strategy:
      fail-fast: false
      matrix:
        image: [windows-2019, windows-2022]
    runs-on: ${{ matrix.image }}
    env:
      CC: gcc
      SUFFIX: windows-${{ matrix.image }}-gcc
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            clang
            autoconf
            automake
            libtool
      - name: Build
        shell: msys2 {0}
        run: |
          autoreconf -i
          ./configure \
            --disable-docs \
            --disable-maintainer-mode \
            --disable-valgrind \
            --with-oniguruma=builtin \
            --disable-shared \
            --enable-static \
            --enable-all-static
          make
          strip jq.exe
      - name: Test
        shell: msys2 {0}
        run: |
          make check
          git diff --exit-code --ignore-submodules
      - name: Upload Test Logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs-${{ env.SUFFIX }}
          retention-days: 7
          path: |
            test-suite.log
            tests/*.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jq-${{ env.SUFFIX }}
          if-no-files-found: error
          retention-days: 7
          path: jq.exe

  dist:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/jq-')
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y automake autoconf
      - name: Create dist
        run: |
          autoreconf -i
          ./configure \
            --disable-docs \
            --disable-maintainer-mode \
            --disable-valgrind \
            --with-oniguruma=builtin
          make dist dist-zip
          git diff --exit-code
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jq-dist
          if-no-files-found: error
          retention-days: 7
          path: |
            jq-*.tar.gz
            jq-*.zip

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    if: startsWith(github.ref, 'refs/tags/jq-')
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Docker metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=match,pattern=jq-(.*),group=1,value=${{ github.ref_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and release Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [linux, macos, windows, dist]
    if: startsWith(github.ref, 'refs/tags/jq-')
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Merge built artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Upload release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir release
          cp artifacts/jq-linux-ubuntu-22.04-gcc-amd64/jq release/jq-linux-amd64
          cp artifacts/jq-linux-ubuntu-22.04-gcc-arm64/jq release/jq-linux-arm64
          cp artifacts/jq-macos-macos-13-clang-amd64/jq release/jq-macos-amd64
          cp artifacts/jq-macos-macos-13-clang-arm64/jq release/jq-macos-arm64
          cp artifacts/jq-windows-windows-2022-gcc/jq.exe release/jq-windows-amd64.exe
          cp artifacts/jq-dist/jq-* release/
          gh release create "$TAG_NAME" --draft --title "jq ${TAG_NAME#jq-}" --generate-notes
          gh release upload "$TAG_NAME" --clobber release/jq-*
