on:
  push:
   tags:
    - 'v*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  make-amd64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v3
      - name: submodule update
        run: |
          git submodule update --init
          git submodule update
      - name: auto reconfigure
        run: autoreconf -fi
      - name: configure
        run: ./configure --with-oniguruma=builtin
      - name: make
        run: make -j8 LDFLAGS=-all-static
      - name: make check
        run: make check
      - name: Check Test Results
        if: always()
        run: cat test-suite.log
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: ./jq
          asset_name: jq-amd64
          asset_content_type: application/octet-stream

  make-arm64:
    runs-on: [self-hosted, linux, ARM64]
    needs: create-release
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: install required packages
        run: |
          apt update -y
          apt install autoconf libtool build-essential git bison -y
      - name: submodule update
        run: |
          git submodule update --init
          git submodule update
      - name: auto reconfigure
        run: autoreconf -fi
      - name: configure
        run: ./configure --with-oniguruma=builtin
      - name: make
        run: make -j8 LDFLAGS=-all-static
      - name: make check
        run: make check
      - name: Check Test Results
        if: always()
        run: cat test-suite.log
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url }}
          asset_path: ./jq
          asset_name: jq-arm64
          asset_content_type: application/octet-stream
